### ISSUE TITLE
Автоматический прием в друзья

### ISSUE THREAD

**Issue by metroyanno** [TiberiumN/VBot#2]
Реализовать плагин для автоматического приёма заявок в друзья

**Comment by TiberiumPY** [comment]
@metroyanno
В принципе можно реализовать проверку на друзей раз в минуту, и добавление всех.
Может есть способ лучше, я посмотрю.

**Comment by metroyanno** [comment]
У меня написаный есть, в течении дня Pull Request кину

**Comment by TiberiumPY** [comment]
@metroyanno о, круто!

**Comment by metroyanno** [comment]
Отправил Pull Request

**Comment by metroyanno** [comment]
@TiberiumPY

**Comment by TiberiumPY** [comment]
@metroyanno Я сейчас сделаю получше - в боте добавлю функцию для использования в плагинах - ты специальным декоратором помечаешь функцию @schedule(30), и она запускается каждые 30 секунд
