### ISSUE TITLE
Долго выполняется команда !отзеркаль

### ISSUE THREAD

**Issue by Volcharka** [TiberiumN/VBot#24]
Зеркалит фотографию где-то 4-5 секунд, в это время не реагирует на другие команды

**Comment by TiberiumN** [comment]
Это зависит от интернет подключения больше всего (и от мощности компьютера)
А вот насчёт того, что не реагирует на другие команды - придётся что-то делать с асинхронностью.
Вместо простого await нужно как-то будет await'ить плагины, чтобы они не блокировали главный поток программы.
В своём боте на Nim я решил, в питоне по сути то решаемо

**Comment by TiberiumN** [comment]
@Myzon почему это было закрыто?
Разве проблема была решена?

**Comment by Myzon** [comment]
Не работало из-за синхронности, сейчас должно работать. А то, что медленно - это я не знаю как упростить ещё. Всё, что плагин делает - скачать, отзеркалить, загрузить.

**Comment by TiberiumN** [comment]
@Myzon а можно коммит, где ты пофиксил эту проблему?
Пожалуйста, всегда в коммитах указывай решённые проблемы в названии коммита, например "Fixes #24"

**Comment by Myzon** [comment]
@TiberiumN https://github.com/TiberiumN/VBot/commit/cb7921e48d14b0e8de7b3adff032c43e2b68cfa1
Хорошо, буду писать
