### ISSUE TITLE
Голосовые сообщения

### ISSUE THREAD

**Issue by Volcharka** [TiberiumN/VBot#6]
Отправляет голосовые сообщения через раз, пишет "Я не смог это произнести :("

**Comment by TiberiumPY** [comment]
Можно лог ошибки?

**Comment by Volcharka** [comment]
В логе только это:
←[35m14:19:19←[0m - ←[36mINFO←[0m - ←[39mКоманда 'скажи' из ЛС 362084749 с аргументами ['тест']←[0m
